Controllers/HomeController.cs
using affnt.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace affnt.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult Matches()
        {
            Person per =db.People
                       .Where(p => p.Gender == "F")
                       .OrderBy(p => p.City)
                       .ToList()
                       .FirstOrDefault();
            return View(per);
        }
    }
}

Controllers/MatchesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using affnt.Models;

namespace affnt.Controllers
{
    public class MatchesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Matches
        public ActionResult Index()
        {
            Person per = db.People
                        .Where(p => p.Gender == "F")
                        .Where(p => p.Approval==false)
                        .OrderBy(p => p.City)
                        .FirstOrDefault();
            return View(per);
        }


        public ActionResult Create()
        {
            return View();
        }





    }
       
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>AFFNT</h1>
    <p class="lead">This Application is made for people from smarter people</p>
    @Html.ActionLink("Find People", "Matches", new { @class="btn btn-primary btn-lg"})
</div>

Views/Home/Matches.cshtml
@model affnt.Models.Person

@{
    ViewBag.Title = "Matches";
}

<h2>Matches</h2>

<div>
    <h4>
        @Html.DisplayFor(model=>model.Name)
    </h4>
    <hr />
    <dl class="dl-horizontal">
      
        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

       

    </dl>
</div>
<p>
    <a href="Like" class="btn btn-primary btn-lg">Like</a>
    <a href="Pass" class="btn btn-primary btn-lg">Pass</a>
       
</p>